[package]
name = "bevy-tetris"
version = "0.1.0"
authors = ["8bit-pudding", "Freynin"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
rand = "0.7.3"
